import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import Modal from "../components/Modal.jsx";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import { getApiError } from "../services/api.js";
import { createAdvisor, listAdvisors, updateAdvisor } from "../services/advisor.service.js";
import { useAuthStore } from "../store/auth.store.js";

function AdvisorForm({ initial, onSubmit, onCancel, pending }) {
  const [form, setForm] = useState({ name: initial?.name || "", email: initial?.email || "", password: "", isActive: initial?.isActive !== false }); const [error, setError] = useState("");
  function change(event) { const { name, value, type, checked } = event.target; setForm({ ...form, [name]: type === "checkbox" ? checked : value }); }
  async function submit(event) { event.preventDefault(); setError(""); if (form.name.trim().length < 2 || form.name.trim().length > 120) return setError("Name must be between 2 and 120 characters."); if (!initial && (!/^\S+@\S+\.\S+$/.test(form.email.trim()) || form.password.length < 8)) return setError("Enter a valid email and a password of at least 8 characters."); if (initial && form.email && !/^\S+@\S+\.\S+$/.test(form.email.trim())) return setError("Enter a valid email address."); if (initial && form.password && form.password.length < 8) return setError("Password must be at least 8 characters."); try { await onSubmit({ name: form.name.trim(), email: form.email.trim(), password: form.password || undefined, ...(initial ? { isActive: form.isActive } : {}) }); } catch (err) { setError(getApiError(err).message); } }
  return <form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium">Name<input name="name" required value={form.name} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label><label className="block text-sm font-medium">Email<input name="email" type="email" required={!initial} value={form.email} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label><label className="block text-sm font-medium">{initial ? "New password (optional)" : "Password"}<input name="password" type="password" required={!initial} value={form.password} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label>{initial && <label className="flex items-center gap-3 text-sm font-medium"><input name="isActive" type="checkbox" checked={form.isActive} onChange={change} className="h-4 w-4 accent-teal" />Active advisor</label>}{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onCancel} className="focus-ring rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={pending} className="focus-ring rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white disabled:opacity-50">{pending ? "Saving…" : "Save advisor"}</button></div></form>;
}

export default function AdvisorsPage() {
  const brokerageId = useAuthStore((state) => state.user?.brokerageId); const qc = useQueryClient(); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(""); const query = useQuery({ queryKey: ["advisors", brokerageId], queryFn: () => listAdvisors(brokerageId), enabled: Boolean(brokerageId) }); const save = useMutation({ mutationFn: (data) => editing === "new" ? createAdvisor({ brokerageId, data }) : updateAdvisor({ brokerageId, advisorId: editing.id, data }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["advisors", brokerageId] }); setEditing(null); setMessage("Advisor saved."); }, onError: (error) => setMessage(getApiError(error).message) });
  if (query.isLoading) return <LoadingState label="Loading advisors…" />; if (query.isError) return <ErrorState message={query.error?.response?.data?.message || "Unable to load advisors."} onRetry={() => query.refetch()} />;
  return <section><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Team</p><h1 className="font-display text-4xl tracking-tight">Advisors</h1><p className="mt-3 text-ink-soft">Manage brokerage advisors from this workspace.</p></div><button onClick={() => { setMessage(""); setEditing("new"); }} className="focus-ring min-h-11 rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white">+ Add Advisor</button></div>{message && <p className="mt-5 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900" role="status">{message}</p>}<div className="mt-8 overflow-x-auto rounded-xl border border-line bg-surface"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-line bg-paper text-xs uppercase tracking-wide text-ink-soft"><tr><th className="px-5 py-4">Name</th><th className="px-3 py-4">Email</th><th className="px-3 py-4">Status</th><th className="px-3 py-4">Active cases</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{query.data?.length ? query.data.map((advisor) => <tr key={advisor.id} className="border-b border-line last:border-b-0"><td className="px-5 py-5 font-semibold">{advisor.name}</td><td className="px-3 py-5 text-ink-soft">{advisor.email}</td><td className="px-3 py-5"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${advisor.isActive ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "border-line bg-slate-100 text-ink-soft"}`}>{advisor.isActive ? "Active" : "Inactive"}</span></td><td className="px-3 py-5 font-semibold">{advisor.activeCaseCount ?? 0}</td><td className="px-5 py-5"><button onClick={() => { setMessage(""); setEditing(advisor); }} className="focus-ring rounded-lg border border-line px-3 py-2 text-xs font-semibold">Edit</button></td></tr>) : <tr><td colSpan="5" className="px-5 py-16 text-center text-sm text-ink-soft">No advisors yet. Add the first advisor to this brokerage.</td></tr>}</tbody></table></div>{editing && <Modal title={editing === "new" ? "Add advisor" : "Edit advisor"} onClose={() => setEditing(null)}><AdvisorForm initial={editing === "new" ? undefined : editing} onCancel={() => setEditing(null)} onSubmit={(data) => save.mutateAsync(data)} pending={save.isPending} /></Modal>}</section>;
}
