import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRef, useState } from "react";
import Modal from "../components/Modal.jsx";
import DocumentStatusBadge from "../components/DocumentStatusBadge.jsx";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import { getApiError } from "../services/api.js";
import { getClientDocument, listClientDocuments, uploadClientDocument } from "../services/document.service.js";

const terminal = new Set(["APPROVED", "FAILED"]); const accepted = ["application/pdf", "image/jpeg", "image/png"];
function date(value) { return value ? new Date(value).toLocaleString() : "—"; }
export default function ClientDocumentsPage() {
  const inputRef = useRef(null); const qc = useQueryClient(); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(""); const [success, setSuccess] = useState("");
  const query = useQuery({ queryKey: ["client", "documents"], queryFn: listClientDocuments, refetchInterval: (current) => current.state.data?.some((doc) => !terminal.has(doc.status)) ? 2500 : false });
  const upload = useMutation({ mutationFn: uploadClientDocument, onSuccess: (document) => { qc.invalidateQueries({ queryKey: ["client", "documents"] }); setSuccess(`${document.originalName} uploaded successfully.`); setMessage(""); if (inputRef.current) inputRef.current.value = ""; }, onError: (error) => setMessage(getApiError(error).message) });
  function choose(event) { setMessage(""); setSuccess(""); const file = event.target.files?.[0]; if (!file) return; if (!accepted.includes(file.type)) return setMessage("Only PDF, JPG, JPEG, and PNG files are supported."); if (file.size > 10 * 1024 * 1024) return setMessage("The document must be 10 MB or smaller."); upload.mutate(file); }
  if (query.isLoading) return <LoadingState label="Loading your documents…" />; if (query.isError) return <ErrorState message={query.error?.response?.data?.message || "Unable to load your documents."} onRetry={() => query.refetch()} />;
  const documents = query.data || [];
  return <section className="max-w-5xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Client portal</p><h1 className="font-display text-4xl tracking-tight">Documents</h1><p className="mt-3 text-ink-soft">Upload the documents your brokerage needs for your case.</p><div className="mt-8 rounded-2xl border border-dashed border-teal/50 bg-teal/5 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><h2 className="font-display text-2xl">Add a document</h2><p className="mt-2 text-sm text-ink-soft">PDF, JPG, JPEG, or PNG · maximum 10 MB</p></div><label className={`focus-ring inline-flex min-h-11 cursor-pointer items-center justify-center rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white ${upload.isPending ? "pointer-events-none opacity-50" : ""}`}><input ref={inputRef} type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={choose} disabled={upload.isPending} className="sr-only" />{upload.isPending ? "Uploading…" : "Choose file"}</label></div>{message && <p className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{message}</p>}{success && <p className="mt-5 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-900" role="status">{success}</p>}</div><div className="mt-8 overflow-hidden rounded-xl border border-line bg-surface">{documents.length ? documents.map((document) => <button key={document._id} type="button" onClick={() => setSelected(document._id)} className="focus-ring grid w-full gap-4 border-b border-line p-5 text-left last:border-b-0 hover:bg-paper md:grid-cols-[1.5fr_0.8fr_1fr_1fr] md:items-center"><div><p className="break-words font-semibold">{document.originalName}</p>{document.failureReason && <p className="mt-1 text-sm text-danger">{document.failureReason}</p>}</div><DocumentStatusBadge status={document.status} /><p className="text-sm text-ink-soft">Uploaded {date(document.createdAt)}</p><p className="text-sm text-ink-soft">Checked {date(document.checkedAt)}</p></button>) : <div className="p-12 text-center"><p className="font-display text-2xl">No documents uploaded yet.</p><p className="mt-3 text-sm text-ink-soft">Choose a file above to get started.</p></div>}</div>{selected && <DocumentDetail id={selected} onClose={() => setSelected(null)} />}</section>;
}

function DocumentDetail({ id, onClose }) { const query = useQuery({ queryKey: ["client", "document", id], queryFn: () => getClientDocument(id) }); return <Modal title="Document details" onClose={onClose}>{query.isLoading ? <LoadingState label="Loading document…" /> : query.isError ? <ErrorState message={query.error?.response?.data?.message || "Unable to load document."} /> : <div className="space-y-4 text-sm"><div><p className="text-xs uppercase tracking-wide text-ink-soft">Filename</p><p className="mt-1 break-words font-medium">{query.data.originalName}</p></div><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wide text-ink-soft">Status</span><DocumentStatusBadge status={query.data.status} /></div><div><p className="text-xs uppercase tracking-wide text-ink-soft">Uploaded</p><p className="mt-1">{date(query.data.createdAt)}</p></div>{query.data.failureReason && <div className="rounded-lg bg-red-50 p-3 text-danger"><p className="font-semibold">Why it failed</p><p className="mt-1">{query.data.failureReason}</p></div>}</div>}</Modal>; }
