import { useQuery } from "@tanstack/react-query";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { getClientCase } from "../services/client.service.js";
import { PIPELINE_STAGES, STAGE_LABELS } from "../utils/pipeline.js";

export default function ClientCasePage() {
  const query = useQuery({ queryKey: ["client", "case"], queryFn: getClientCase });
  if (query.isLoading) return <LoadingState label="Loading your case…" />;
  if (query.isError) { if (query.error?.response?.status === 404) return <EmptyCase />; return <ErrorState message={query.error?.response?.data?.message || "Unable to load your case."} onRetry={() => query.refetch()} />; }
  const item = query.data; const brokerage = typeof item.brokerageId === "object" ? item.brokerageId?.name : null; const advisor = typeof item.assignedAdvisorId === "object" ? item.assignedAdvisorId : null; const currentIndex = PIPELINE_STAGES.indexOf(item.status);
  return <section className="max-w-5xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Client portal</p><h1 className="font-display text-4xl tracking-tight">Your case</h1><p className="mt-3 text-ink-soft">A clear view of where your mortgage application stands.</p><div className="mt-8 rounded-2xl bg-ink p-6 text-white shadow-raised sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><p className="text-xs uppercase tracking-[0.18em] text-white/55">Applicant</p><h2 className="mt-2 font-display text-3xl">{item.firstName} {item.lastName}</h2>{brokerage && <p className="mt-2 text-sm text-white/65">{brokerage}</p>}</div><StatusBadge status={item.status} /></div><div className="mt-8 border-t border-white/15 pt-6"><p className="text-xs uppercase tracking-[0.18em] text-white/55">Current stage</p><p className="mt-2 font-display text-2xl">{STAGE_LABELS[item.status] || item.status}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">{stageMessage(item.status)}</p></div><CaseProgress status={item.status} currentIndex={currentIndex} /></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><InfoCard label="Contact email" value={item.email || "Not provided"} /><InfoCard label="Phone" value={item.phone || "Not provided"} /><InfoCard label="Assigned advisor" value={advisor?.name || "Your brokerage will assign an advisor."} detail={advisor?.email} /></div></section>;
}

function CaseProgress({ status, currentIndex }) { if (status === "LOST") return <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-danger"><strong>Case closed</strong><p className="mt-1">This application is currently marked as lost.</p></div>; const stages = PIPELINE_STAGES.filter((stage) => stage !== "LOST"); return <div className="mt-8 overflow-x-auto"><div className="flex min-w-[620px] items-start">{stages.map((stage, index) => { const done = currentIndex >= PIPELINE_STAGES.indexOf(stage); const current = status === stage; return <div key={stage} className="flex flex-1 items-start"><div className="flex min-w-0 flex-col items-center text-center"><span className={`flex h-8 w-8 items-center justify-center rounded-full border text-xs font-semibold ${current ? "border-teal bg-teal text-ink" : done ? "border-white/50 bg-white/20 text-white" : "border-white/25 text-white/45"}`}>{done && !current ? "✓" : index + 1}</span><span className={`mt-2 text-xs ${current ? "font-semibold text-white" : done ? "text-white/75" : "text-white/45"}`}>{STAGE_LABELS[stage]}</span></div>{index < stages.length - 1 && <span className={`mt-4 h-px flex-1 ${currentIndex > PIPELINE_STAGES.indexOf(stage) ? "bg-white/50" : "bg-white/20"}`} />}</div>; })}</div></div>; }
function stageMessage(status) { const messages = { NEW: "Your case has been received and is ready for the next conversation.", CONTACTED: "Your advisor has started the conversation about your application.", QUALIFIED: "Your information is being reviewed for the next application step.", APPLICATION: "Your application is in progress with the brokerage.", WON: "Your application has reached its successful final stage." }; return messages[status] || "Your case status is being reviewed by the brokerage."; }
function InfoCard({ label, value, detail }) { return <div className="rounded-xl border border-line bg-surface p-6"><p className="text-xs uppercase tracking-wide text-ink-soft">{label}</p><p className="mt-2 break-words font-medium">{value}</p>{detail && <p className="mt-1 break-words text-sm text-ink-soft">{detail}</p>}</div>; }
function EmptyCase() { return <section className="max-w-2xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Client portal</p><h1 className="font-display text-4xl tracking-tight">Your case</h1><div className="mt-8 rounded-2xl border border-dashed border-line bg-surface p-10 text-center"><p className="font-display text-2xl">No active case is linked to this account.</p><p className="mt-3 text-sm leading-6 text-ink-soft">Your brokerage will need to link a case before it appears here.</p></div></section>; }
