import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import Modal from "../components/Modal.jsx";
import AutomationForm from "../components/AutomationForm.jsx";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { useAuthStore } from "../store/auth.store.js";
import { createEmailTemplate, deleteEmailTemplate, listEmailTemplates, updateEmailTemplate } from "../services/email-template.service.js";
import { STAGE_LABELS } from "../utils/pipeline.js";

function formData(item) { return { name: item.name, subject: item.subject, body: item.body, stage: item.stage, isActive: item.isActive }; }
export default function EmailTemplatesPage() {
  const brokerageId = useAuthStore((state) => state.user?.brokerageId); const qc = useQueryClient(); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(""); const query = useQuery({ queryKey: ["email-templates", brokerageId], queryFn: () => listEmailTemplates(brokerageId), enabled: Boolean(brokerageId) });
  const invalidate = () => qc.invalidateQueries({ queryKey: ["email-templates", brokerageId] }); const save = useMutation({ mutationFn: (data) => editing === "new" ? createEmailTemplate({ brokerageId, data }) : updateEmailTemplate({ brokerageId, templateId: editing._id, data }), onSuccess: () => { invalidate(); setEditing(null); setMessage(""); }, onError: (error) => setMessage(error.response?.status === 409 ? "An active template already exists for this stage." : error.response?.data?.message || "Unable to save template.") }); const remove = useMutation({ mutationFn: (templateId) => deleteEmailTemplate({ brokerageId, templateId }), onSuccess: invalidate, onError: (error) => setMessage(error.response?.data?.message || "Unable to delete template.") });
  if (query.isLoading) return <LoadingState label="Loading email templates…" />; if (query.isError) return <ErrorState message={query.error?.response?.data?.message || "Unable to load email templates."} onRetry={() => query.refetch()} />;
  return <section><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Automation</p><h1 className="font-display text-4xl tracking-tight">Email templates</h1><p className="mt-3 text-ink-soft">Shape the messages clients receive as their application moves.</p></div><button onClick={() => { setMessage(""); setEditing("new"); }} className="focus-ring min-h-11 rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white">+ New template</button></div>{message && <p className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{message}</p>}<div className="mt-8 grid gap-4 lg:grid-cols-2">{query.data?.length ? query.data.map((template) => <article key={template._id} className="rounded-xl border border-line bg-surface p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{template.name}</h2><StatusBadge status={template.stage} /></div><p className="mt-2 text-sm text-ink-soft">{template.subject}</p><p className="mt-2 text-xs text-ink-soft">Trigger stage: <span className="font-semibold text-ink">{STAGE_LABELS[template.stage] || template.stage}</span></p></div><span className={`text-xs font-semibold ${template.isActive ? "text-teal-dark" : "text-ink-soft"}`}>{template.isActive ? "Active" : "Inactive"}</span></div><div className="mt-5 flex gap-2"><button onClick={() => { setMessage(""); setEditing(template); }} className="focus-ring rounded-lg border border-line px-3 py-2 text-sm font-semibold">Edit</button><button onClick={() => remove.mutate(template._id)} disabled={remove.isPending} className="focus-ring rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-danger">Delete</button></div></article>) : <div className="rounded-xl border border-dashed border-line p-12 text-center text-sm text-ink-soft lg:col-span-2">No email templates yet. Create the first one for a pipeline stage.</div>}</div>{editing && <Modal title={editing === "new" ? "Create email template" : "Edit email template"} onClose={() => setEditing(null)}><AutomationForm type="template" initial={editing === "new" ? undefined : formData(editing)} onCancel={() => setEditing(null)} onSubmit={(data) => save.mutateAsync(data)} isPending={save.isPending} /></Modal>}</section>;
}
