import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import DocumentStatusBadge from "../components/DocumentStatusBadge.jsx";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import Modal from "../components/Modal.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { getApiError } from "../services/api.js";
import { listAvailableAdvisors } from "../services/advisor.service.js";
import { getLeadDocumentView, listLeadDocuments } from "../services/document.service.js";
import { convertLeadToClient, getLead, updateLead, updateLeadStatus } from "../services/lead.service.js";
import { useAuthStore } from "../store/auth.store.js";
import { PIPELINE_STAGES, STAGE_LABELS } from "../utils/pipeline.js";

export default function LeadDetailPage() {
  const { id } = useParams(); const user = useAuthStore((state) => state.user); const qc = useQueryClient();
  const [message, setMessage] = useState(""); const [showConversion, setShowConversion] = useState(false);
  const canMove = ["brokerageAdmin", "advisor", "platformAdmin"].includes(user?.role); const canAssign = ["brokerageAdmin", "platformAdmin"].includes(user?.role); const canConvert = ["brokerageAdmin", "advisor", "platformAdmin"].includes(user?.role);
  const leadQuery = useQuery({ queryKey: ["lead", id], queryFn: () => getLead(id) }); const lead = leadQuery.data;
  const advisors = useQuery({ queryKey: ["advisors", user?.brokerageId], queryFn: () => listAvailableAdvisors(user.brokerageId), enabled: Boolean(user?.brokerageId && canAssign) });
  const documents = useQuery({ queryKey: ["lead", id, "documents"], queryFn: () => listLeadDocuments(id), enabled: Boolean(id), refetchInterval: (current) => current.state.data?.some((doc) => ["UPLOADED", "PROCESSING"].includes(doc.status)) ? 2500 : false });
  const invalidate = () => { qc.invalidateQueries({ queryKey: ["lead", id] }); qc.invalidateQueries({ queryKey: ["leads"] }); qc.invalidateQueries({ queryKey: ["dashboard", "pipeline"] }); };
  const statusMutation = useMutation({ mutationFn: ({ status, version }) => updateLeadStatus(id, status, version), onSuccess: () => { setMessage(""); invalidate(); }, onError: (error) => { setMessage(error.response?.status === 409 ? "This lead was updated elsewhere. Refreshing the latest version." : getApiError(error).message); invalidate(); } });
  const advisorMutation = useMutation({ mutationFn: (assignedAdvisorId) => updateLead(id, { assignedAdvisorId: assignedAdvisorId || null }), onSuccess: invalidate, onError: (error) => setMessage(getApiError(error).message) });
  const conversionMutation = useMutation({ mutationFn: (password) => convertLeadToClient(id, password), onSuccess: () => { setShowConversion(false); setMessage("Lead converted to a client successfully."); invalidate(); }, onError: (error) => setMessage(error.response?.status === 409 ? "This lead has already been converted or conflicts with an existing client account." : getApiError(error).message) });
  if (leadQuery.isLoading) return <LoadingState label="Loading lead…" />; if (leadQuery.isError) return <ErrorState message={leadQuery.error?.response?.data?.message || "Lead not found."} />;
  return <section className="max-w-5xl"><Link to="/leads" className="focus-ring text-sm font-semibold text-teal-dark hover:underline">← Back to leads</Link><div className="mt-6 flex flex-col justify-between gap-5 border-b border-line pb-7 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Lead detail</p><h1 className="font-display text-4xl tracking-tight">{lead.firstName} {lead.lastName}</h1><p className="mt-3 text-ink-soft">Created {new Date(lead.createdAt).toLocaleDateString()}</p></div><StatusBadge status={lead.status} /></div>{message && <p className="mt-5 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{message}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Contact details</h2><dl className="mt-6 grid gap-5 sm:grid-cols-2">{[["Email", lead.email || "Not provided"], ["Phone", lead.phone || "Not provided"], ["Source", lead.source || "manual"], ["Version", lead.version ?? 0], ["Updated", lead.updatedAt ? new Date(lead.updatedAt).toLocaleString() : "—"], ["Notes", lead.notes || "No notes"]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-ink-soft">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value}</dd></div>)}</dl></div><div className="space-y-5"><div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Pipeline status</h2>{canMove && <select value={lead.status} disabled={statusMutation.isPending} onChange={(event) => statusMutation.mutate({ status: event.target.value, version: lead.version ?? 0 })} className="focus-ring mt-5 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm">{PIPELINE_STAGES.map((stage) => <option key={stage} value={stage}>{STAGE_LABELS[stage]}</option>)}</select>}</div><div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Advisor</h2>{canAssign ? <select value={lead.assignedAdvisorId?._id || lead.assignedAdvisorId || ""} disabled={advisors.isLoading || advisorMutation.isPending} onChange={(event) => advisorMutation.mutate(event.target.value)} className="focus-ring mt-5 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm"><option value="">Unassigned</option>{advisors.data?.map((advisor) => <option key={advisor.id} value={advisor.id}>{advisor.name}</option>)}</select> : <p className="mt-5 text-sm text-ink-soft">{lead.assignedAdvisorId?.name || "Unassigned"}</p>}</div>{canConvert && <ConversionCard lead={lead} onOpen={() => setShowConversion(true)} />}</div></div><LeadDocumentsSection query={documents} leadId={id} />{showConversion && <ConversionModal pending={conversionMutation.isPending} onClose={() => setShowConversion(false)} onSubmit={(password) => conversionMutation.mutateAsync(password)} />}</section>;
}

function LeadDocumentsSection({ query, leadId }) { const view = useMutation({ mutationFn: (documentId) => getLeadDocumentView(leadId, documentId), onSuccess: ({ url }) => window.open(url, "_blank", "noopener,noreferrer") }); if (query.isLoading) return <section className="mt-8 rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Documents</h2><LoadingState label="Loading documents…" /></section>; if (query.isError) return <section className="mt-8"><h2 className="mb-3 font-display text-2xl">Documents</h2><ErrorState message={query.error?.response?.data?.message || "Unable to load lead documents."} onRetry={() => query.refetch()} /></section>; const docs = query.data || []; return <section className="mt-8 rounded-xl border border-line bg-surface p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-display text-2xl">Documents</h2><p className="mt-1 text-sm text-ink-soft">Read-only documents uploaded by the client.</p></div><span className="text-sm text-ink-soft">{docs.length} document{docs.length === 1 ? "" : "s"}</span></div>{docs.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{docs.map((doc) => <article key={doc._id} className="flex min-w-0 min-h-[220px] flex-col gap-3 rounded-lg border border-line p-4"><div className="min-w-0 min-h-16"><p className="break-words font-semibold">{doc.originalName}</p>{doc.status === "FAILED" && doc.failureReason && <p className="mt-1 text-sm text-danger">{doc.failureReason}</p>}</div><div className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs uppercase tracking-wide text-ink-soft">Type</p><p className="mt-1 break-words">{doc.mimeType || "Unknown"}</p></div><div><p className="text-xs uppercase tracking-wide text-ink-soft">Size</p><p className="mt-1">{formatDocumentSize(doc.size)}</p></div></div><div className="mt-auto flex flex-wrap items-start gap-2 border-t border-line pt-4"><DocumentStatusBadge status={doc.status} /><div className="text-xs leading-5 text-ink-soft">Uploaded {formatDocumentDate(doc.createdAt)}{doc.checkedAt && <><br />Checked {formatDocumentDate(doc.checkedAt)}</>}</div></div><button type="button" disabled={view.isPending} onClick={() => view.mutate(doc._id)} className="focus-ring rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:border-teal disabled:opacity-50">{view.isPending ? "Opening…" : "View document"}</button></article>)}</div> : <div className="mt-5 rounded-lg border border-dashed border-line p-8 text-center text-sm text-ink-soft">No documents uploaded yet.</div>}</section>; }
function formatDocumentSize(bytes) { if (!bytes) return "—"; if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function formatDocumentDate(value) { return value ? new Date(value).toLocaleString() : "—"; }
function ConversionCard({ lead, onOpen }) { if (lead.clientId) return <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="font-display text-2xl text-emerald-950">Converted to client</h2><p className="mt-2 text-sm text-emerald-900">This lead is linked to a client account.</p>{lead.convertedAt && <p className="mt-2 text-xs text-emerald-800">Converted {new Date(lead.convertedAt).toLocaleDateString()}</p>}</div>; if (!lead.email) return <div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Convert to client</h2><p className="mt-2 text-sm text-ink-soft">A lead email is required before a client account can be created.</p></div>; return <div className="rounded-xl border border-teal/40 bg-teal/5 p-6"><h2 className="font-display text-2xl">Convert to client</h2><p className="mt-2 text-sm text-ink-soft">Create a client account from this lead.</p><button onClick={onOpen} className="focus-ring mt-5 min-h-11 rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white">Convert to Client</button></div>; }
function ConversionModal({ pending, onClose, onSubmit }) { const [password, setPassword] = useState(""); const [error, setError] = useState(""); async function submit(event) { event.preventDefault(); if (password.length < 8) return setError("Temporary password must be at least 8 characters."); setError(""); try { await onSubmit(password); } catch (err) { setError(getApiError(err).message); } } return <Modal title="Convert lead to client" onClose={onClose}><form onSubmit={submit} className="space-y-5"><p className="text-sm leading-6 text-ink-soft">Set a temporary password for the new client account. Share it securely with the client.</p><label className="block text-sm font-medium">Temporary password<input autoFocus required minLength="8" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="focus-ring rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={pending} className="focus-ring rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white disabled:opacity-50">{pending ? "Converting…" : "Create client account"}</button></div></form></Modal>; }
