import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { getApiError } from "../services/api.js";
import { getLead, updateLead, updateLeadStatus } from "../services/lead.service.js";
import { listAvailableAdvisors } from "../services/advisor.service.js";
import { useAuthStore } from "../store/auth.store.js";
import { PIPELINE_STAGES, STAGE_LABELS } from "../utils/pipeline.js";

export default function LeadDetailPage() {
  const { id } = useParams(); const user = useAuthStore((state) => state.user); const qc = useQueryClient(); const [message, setMessage] = useState(""); const canMove = ["brokerageAdmin", "advisor", "platformAdmin"].includes(user?.role); const canAssign = ["brokerageAdmin", "advisor"].includes(user?.role);
  const leadQuery = useQuery({ queryKey: ["lead", id], queryFn: () => getLead(id) }); const lead = leadQuery.data; const advisors = useQuery({ queryKey: ["advisors", user?.brokerageId], queryFn: () => listAvailableAdvisors(user.brokerageId), enabled: Boolean(user?.brokerageId && canAssign) });
  const invalidate = () => { qc.invalidateQueries({ queryKey: ["lead", id] }); qc.invalidateQueries({ queryKey: ["leads"] }); qc.invalidateQueries({ queryKey: ["dashboard", "pipeline"] }); };
  const statusMutation = useMutation({ mutationFn: ({ status, version }) => updateLeadStatus(id, status, version), onSuccess: (result) => { message && setMessage(""); invalidate(); }, onError: (error) => { setMessage(error.response?.status === 409 ? "This lead was updated elsewhere. Refreshing the latest version." : getApiError(error).message); invalidate(); } });
  const advisorMutation = useMutation({ mutationFn: (assignedAdvisorId) => updateLead(id, { assignedAdvisorId: assignedAdvisorId || null }), onSuccess: invalidate, onError: (error) => setMessage(getApiError(error).message) });
  if (leadQuery.isLoading) return <LoadingState label="Loading lead…" />; if (leadQuery.isError) return <ErrorState message={leadQuery.error?.response?.data?.message || "Lead not found."} />;
  return <section className="max-w-5xl"><Link to="/leads" className="focus-ring text-sm font-semibold text-teal-dark hover:underline">← Back to leads</Link><div className="mt-6 flex flex-col justify-between gap-5 border-b border-line pb-7 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Lead detail</p><h1 className="font-display text-4xl tracking-tight">{lead.firstName} {lead.lastName}</h1><p className="mt-3 text-ink-soft">Created {new Date(lead.createdAt).toLocaleDateString()}</p></div><StatusBadge status={lead.status} /></div>{message && <p className="mt-5 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{message}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Contact details</h2><dl className="mt-6 grid gap-5 sm:grid-cols-2">{[["Email", lead.email || "Not provided"], ["Phone", lead.phone || "Not provided"], ["Source", lead.source || "manual"], ["Version", lead.version ?? 0], ["Updated", lead.updatedAt ? new Date(lead.updatedAt).toLocaleString() : "—"], ["Notes", lead.notes || "No notes"]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-ink-soft">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value}</dd></div>)}</dl></div><div className="space-y-5"><div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Pipeline status</h2>{canMove && <select value={lead.status} disabled={statusMutation.isPending} onChange={(event) => statusMutation.mutate({ status: event.target.value, version: lead.version ?? 0 })} className="focus-ring mt-5 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm">{PIPELINE_STAGES.map((stage) => <option key={stage} value={stage}>{STAGE_LABELS[stage]}</option>)}</select>}</div>{canAssign && <div className="rounded-xl border border-line bg-surface p-6"><h2 className="font-display text-2xl">Advisor</h2><select value={lead.assignedAdvisorId?._id || lead.assignedAdvisorId || ""} disabled={advisors.isLoading || advisorMutation.isPending} onChange={(event) => advisorMutation.mutate(event.target.value)} className="focus-ring mt-5 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm"><option value="">Unassigned</option>{advisors.data?.map((advisor) => <option key={advisor.id} value={advisor.id}>{advisor.name}</option>)}</select></div>}</div></div></section>;
}
