import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import Modal from "../components/Modal.jsx";
import AutomationForm from "../components/AutomationForm.jsx";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { useAuthStore } from "../store/auth.store.js";
import { createTaskTrigger, deleteTaskTrigger, listTaskTriggers, updateTaskTrigger } from "../services/task-trigger.service.js";
import { STAGE_LABELS } from "../utils/pipeline.js";

function formData(item) { return { stage: item.stage, title: item.title, description: item.description || "", dueInMinutes: item.dueInMinutes, isActive: item.isActive }; }
export default function TaskTriggersPage() {
  const brokerageId = useAuthStore((state) => state.user?.brokerageId); const qc = useQueryClient(); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(""); const query = useQuery({ queryKey: ["task-triggers", brokerageId], queryFn: () => listTaskTriggers(brokerageId), enabled: Boolean(brokerageId) });
  const invalidate = () => qc.invalidateQueries({ queryKey: ["task-triggers", brokerageId] }); const save = useMutation({ mutationFn: (data) => editing === "new" ? createTaskTrigger({ brokerageId, data }) : updateTaskTrigger({ brokerageId, triggerId: editing._id, data }), onSuccess: () => { invalidate(); setEditing(null); setMessage(""); }, onError: (error) => setMessage(error.response?.status === 409 ? "An identical active task trigger already exists for this stage." : error.response?.data?.message || "Unable to save task trigger.") }); const remove = useMutation({ mutationFn: (triggerId) => deleteTaskTrigger({ brokerageId, triggerId }), onSuccess: invalidate, onError: (error) => setMessage(error.response?.data?.message || "Unable to delete task trigger.") });
  if (query.isLoading) return <LoadingState label="Loading task triggers…" />; if (query.isError) return <ErrorState message={query.error?.response?.data?.message || "Unable to load task triggers."} onRetry={() => query.refetch()} />;
  return <section><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Automation</p><h1 className="font-display text-4xl tracking-tight">Task triggers</h1><p className="mt-3 text-ink-soft">Create consistent follow-up work at each pipeline stage.</p></div><button onClick={() => { setMessage(""); setEditing("new"); }} className="focus-ring min-h-11 rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white">+ New trigger</button></div>{message && <p className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{message}</p>}<div className="mt-8 overflow-hidden rounded-xl border border-line bg-surface">{query.data?.length ? query.data.map((trigger) => <article key={trigger._id} className="grid gap-4 border-b border-line p-5 last:border-b-0 md:grid-cols-[0.8fr_1.4fr_1fr_0.7fr_auto] md:items-center"><div><StatusBadge status={trigger.stage} /></div><div><h2 className="font-semibold">{trigger.title}</h2>{trigger.description && <p className="mt-1 text-sm text-ink-soft">{trigger.description}</p>}</div><p className="text-sm text-ink-soft">Due in <strong className="text-ink">{trigger.dueInMinutes} min</strong></p><p className={`text-sm font-semibold ${trigger.isActive ? "text-teal-dark" : "text-ink-soft"}`}>{trigger.isActive ? "Active" : "Inactive"}<span className="sr-only"> {STAGE_LABELS[trigger.stage]}</span></p><div className="flex gap-2"><button onClick={() => { setMessage(""); setEditing(trigger); }} className="focus-ring rounded-lg border border-line px-3 py-2 text-sm font-semibold">Edit</button><button onClick={() => remove.mutate(trigger._id)} disabled={remove.isPending} className="focus-ring rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-danger">Delete</button></div></article>) : <div className="p-12 text-center text-sm text-ink-soft">No task triggers yet. Create one to automate follow-up.</div>}</div>{editing && <Modal title={editing === "new" ? "Create task trigger" : "Edit task trigger"} onClose={() => setEditing(null)}><AutomationForm type="trigger" initial={editing === "new" ? undefined : formData(editing)} onCancel={() => setEditing(null)} onSubmit={(data) => save.mutateAsync(data)} isPending={save.isPending} /></Modal>}</section>;
}
