import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import ErrorState from "../components/ErrorState.jsx";
import LoadingState from "../components/LoadingState.jsx";
import TaskStatusBadge from "../components/TaskStatusBadge.jsx";
import { getApiError } from "../services/api.js";
import { completeTask, listTasks } from "../services/task.service.js";

const filters = ["", "TODO", "COMPLETED", "CANCELLED"];
function date(value) { return value ? new Date(value).toLocaleString() : "—"; }
function relativeDuration(ms) { const minutes = Math.max(1, Math.round(ms / 60000)); if (minutes < 60) return `${minutes} minute${minutes === 1 ? "" : "s"}`; const hours = Math.round(minutes / 60); return `${hours} hour${hours === 1 ? "" : "s"}`; }
function dueLabel(task) { if (!task.dueAt) return "—"; if (task.status !== "TODO") return date(task.dueAt); const diff = new Date(task.dueAt).getTime() - Date.now(); if (diff < 0) return `Overdue by ${relativeDuration(Math.abs(diff))}`; if (diff <= 24 * 60 * 60 * 1000) return `Due in ${relativeDuration(diff)}`; return date(task.dueAt); }

export default function TasksPage() {
  const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const qc = useQueryClient(); const query = useQuery({ queryKey: ["tasks", { status }], queryFn: () => listTasks(status) });
  const complete = useMutation({ mutationFn: completeTask, onSuccess: () => qc.invalidateQueries({ queryKey: ["tasks"] }), onError: (error) => setMessage(getApiError(error).message) });
  if (query.isLoading) return <LoadingState label="Loading tasks…" />; if (query.isError) return <ErrorState message={query.error?.response?.data?.message || "Unable to load tasks."} onRetry={() => query.refetch()} />;
  const tasks = query.data || [];
  return <section><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-teal-dark">Work queue</p><h1 className="font-display text-4xl tracking-tight">Tasks</h1><p className="mt-3 text-ink-soft">Stay ahead of the next client conversation.</p></div><select aria-label="Filter tasks by status" value={status} onChange={(event) => setStatus(event.target.value)} className="focus-ring min-h-11 rounded-lg border border-line bg-surface px-3 text-sm"><option value="">All statuses</option>{filters.slice(1).map((item) => <option key={item}>{item}</option>)}</select></div>{message && <p className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{message}</p>}<div className="mt-8 overflow-x-auto rounded-xl border border-line bg-surface"><table className="w-full min-w-[900px] table-fixed text-left"><colgroup><col className="w-[16%]" /><col className="w-[16%]" /><col className="w-[32%]" /><col className="w-[14%]" /><col className="w-[12%]" /><col className="w-[10%]" /></colgroup><thead className="border-b border-line bg-paper text-xs font-semibold uppercase tracking-wide text-ink-soft"><tr><th scope="col" className="px-5 py-3">Lead</th><th scope="col" className="px-5 py-3">Advisor</th><th scope="col" className="px-5 py-3">Task</th><th scope="col" className="px-5 py-3">Due</th><th scope="col" className="px-5 py-3">Status</th><th scope="col" className="px-5 py-3">Action</th></tr></thead><tbody>{tasks.length ? tasks.map((task) => <tr key={task._id} className={`border-b border-line last:border-b-0 ${task.overdue ? "border-l-4 border-l-danger bg-red-50/60" : ""}`}><td className="break-words px-5 py-5 align-top text-sm text-ink-soft">{task.leadId?.firstName ? `${task.leadId.firstName} ${task.leadId.lastName || ""}` : "—"}</td><td className="break-words px-5 py-5 align-top text-sm text-ink-soft">{task.advisorId?.name || "Unassigned"}</td><td className="break-words px-5 py-5 align-top"><p className="font-semibold">{task.title}</p>{task.description && <p className="mt-1 whitespace-normal text-sm text-ink-soft">{task.description}</p>}<p className="mt-2 text-xs uppercase tracking-wide text-ink-soft">{task.sourceStage || "—"}</p></td><td className={`break-words px-5 py-5 align-top text-sm ${task.overdue ? "font-semibold text-danger" : "text-ink-soft"}`}>{dueLabel(task)}</td><td className="px-5 py-5 align-top"><TaskStatusBadge status={task.status} /></td><td className="px-5 py-5 align-top">{task.status === "TODO" && <button disabled={complete.isPending} onClick={() => complete.mutate(task._id)} className="focus-ring min-h-11 rounded-lg border border-line px-3 text-sm font-semibold hover:border-teal disabled:opacity-50">Complete</button>}</td></tr>) : <tr><td colSpan="6" className="px-5 py-16 text-center text-sm text-ink-soft">No tasks match this filter.</td></tr>}</tbody></table></div></section>;
}
