import { useState } from "react";
import { getApiError } from "../services/api.js";

const initial = { firstName: "", lastName: "", email: "", phone: "", source: "manual", assignedAdvisorId: "" };
export default function LeadForm({ advisors, onSubmit, onCancel, isPending }) {
  const [form, setForm] = useState(initial); const [error, setError] = useState("");
  function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function submit(event) { event.preventDefault(); setError(""); if (!form.firstName.trim() || !form.lastName.trim()) return setError("First name and last name are required."); if (!form.email.trim() && !form.phone.trim()) return setError("Add an email address or phone number."); try { await onSubmit({ ...form, assignedAdvisorId: form.assignedAdvisorId || undefined }); } catch (err) { setError(getApiError(err).message); } }
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{[["firstName", "First name"], ["lastName", "Last name"]].map(([name, label]) => <label key={name} className="block text-sm font-medium">{label}<input name={name} value={form[name]} onChange={change} required className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label>)}</div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Email<input name="email" type="email" value={form.email} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label><label className="block text-sm font-medium">Phone<input name="phone" value={form.phone} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Source<input name="source" value={form.source} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5" /></label><label className="block text-sm font-medium">Assigned advisor<select name="assignedAdvisorId" value={form.assignedAdvisorId} onChange={change} className="focus-ring mt-2 block w-full rounded-lg border border-line bg-surface px-3 py-2.5"><option value="">Unassigned</option>{advisors?.map((advisor) => <option key={advisor.id} value={advisor.id}>{advisor.name} · {advisor.email}</option>)}</select></label></div>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-danger" role="alert">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onCancel} className="focus-ring rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={isPending} className="focus-ring rounded-lg bg-teal px-4 py-2.5 text-sm font-semibold text-ink hover:bg-teal-dark hover:text-white disabled:opacity-50">{isPending ? "Creating…" : "Create lead"}</button></div></form>;
}
