import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { getApiError } from "../services/api.js";
import { createTallyIntegration, deleteTallyIntegration, listTallyIntegrations, updateTallyIntegration } from "../services/platform.service.js";

export default function TallyIntegrationsPanel({ brokerageId, onMessage }) {
  const [formId, setFormId] = useState(""); const qc = useQueryClient(); const queryKey = ["platform", "tally-integrations", brokerageId];
  const query = useQuery({ queryKey, queryFn: () => listTallyIntegrations(brokerageId) });
  const refresh = () => qc.invalidateQueries({ queryKey });
  const create = useMutation({ mutationFn: () => createTallyIntegration({ brokerageId, formId }), onSuccess: () => { setFormId(""); onMessage("Tally integration added."); refresh(); }, onError: (error) => onMessage(getApiError(error).message) });
  const update = useMutation({ mutationFn: ({ integrationId, data }) => updateTallyIntegration({ brokerageId, integrationId, data }), onSuccess: () => { onMessage("Tally integration updated."); refresh(); }, onError: (error) => onMessage(getApiError(error).message) });
  const remove = useMutation({ mutationFn: (integrationId) => deleteTallyIntegration({ brokerageId, integrationId }), onSuccess: () => { onMessage("Tally integration deactivated."); refresh(); }, onError: (error) => onMessage(getApiError(error).message) });
  function submit(event) { event.preventDefault(); if (!formId.trim()) return onMessage("Enter a Tally form ID."); create.mutate(); }
  return <div className="mt-6 border-t border-line pt-5"><h3 className="font-display text-xl">Tally integrations</h3><p className="mt-1 text-sm text-ink-soft">Map Tally form submissions to this brokerage.</p><form onSubmit={submit} className="mt-4 flex flex-col gap-2 sm:flex-row"><input aria-label="Tally form ID" value={formId} onChange={(event) => setFormId(event.target.value)} placeholder="Tally form ID" className="focus-ring min-h-10 flex-1 rounded-lg border border-line bg-surface px-3 text-sm" /><button disabled={create.isPending} className="focus-ring min-h-10 rounded-lg bg-teal px-3 py-2 text-sm font-semibold disabled:opacity-50">Add form</button></form>{query.isLoading ? <p className="mt-4 text-sm text-ink-soft">Loading integrations…</p> : query.isError ? <p className="mt-4 text-sm text-danger">Unable to load Tally integrations.</p> : query.data?.length ? <div className="mt-4 space-y-2">{query.data.map((integration) => <div key={integration.id} className="flex flex-col justify-between gap-3 rounded-lg border border-line p-3 sm:flex-row sm:items-center"><div><p className="font-medium">{integration.formId}</p><p className="text-xs text-ink-soft">{integration.active ? "Active" : "Inactive"} · Updated {new Date(integration.updatedAt).toLocaleDateString()}</p></div><div className="flex gap-2"><button onClick={() => update.mutate({ integrationId: integration.id, data: { active: !integration.active } })} className="focus-ring rounded-lg border border-line px-3 py-2 text-xs font-semibold">{integration.active ? "Deactivate" : "Activate"}</button>{integration.active && <button onClick={() => { if (window.confirm("Deactivate this Tally integration?")) remove.mutate(integration.id); }} className="focus-ring rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-danger">Remove</button>}</div></div>)}</div> : <p className="mt-4 rounded-lg border border-dashed border-line p-4 text-sm text-ink-soft">No Tally forms configured.</p>}</div>;
}
